apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-frontend.configmapName" . }}
  labels:
    {{- include "todo-frontend.labels" . | nindent 4 }}
data:
  NEXT_PUBLIC_API_URL: {{ .Values.config.apiUrl | quote }}
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
