apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-backend.configmapName" . }}
  labels:
    {{- include "todo-backend.labels" . | nindent 4 }}
data:
  CORS_ORIGINS: {{ .Values.config.corsOrigins | quote }}
  DEBUG: {{ .Values.config.debug | quote }}
  AI_PROVIDER: {{ .Values.config.aiProvider | quote }}
